"""Generate the paper-ready LaTeX tables for ``docs/final_paper``.

This script is the *only* place that converts validated project artifacts
(CSV/JSON files under ``outputs/`` and ``docs/``) into the LaTeX tables used by
the paper.  No numerical result is hard-coded here: every cell is read from a
validated source artifact, so that if an underlying result changes the tables
can be regenerated by re-running this script.

Sources (see ``docs/final_paper/README.md`` and ``EVIDENCE_MAP.md``):

  * KITTI in-domain metrics   -> outputs/milestone_5/metrics/kitti_validation/*.json
  * KITTI comparison tables   -> outputs/milestone_5/figures/*.csv
  * Waymo external metrics    -> outputs/milestone_6/waymo_external_validation/*.json / tables/*.csv
  * Generalization analysis   -> outputs/milestone_6/generalization_analysis/tables/*.csv
  * Robustness / safety       -> outputs/milestone_7/object_size_analysis/*.csv
                                 outputs/milestone_7/safety_error_analysis/*.csv
                                 outputs/milestone_7/deployment_tradeoff/*.csv
  * Dataset harmonization     -> docs/milestone_2/*.csv

Usage::

    python scripts/final_paper/generate_tables.py

Output: ``docs/final_paper/tables/*.tex`` (one self-contained table per file).
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "final_paper" / "tables"

DETECTOR_ORDER = ["yolo", "rtdetr", "faster_rcnn", "retinanet"]
DISPLAY = {
    "yolo": "YOLOv8s",
    "rtdetr": "RT-DETR-L",
    "faster_rcnn": "Faster R-CNN",
    "retinanet": "RetinaNet",
}
CLASS_DISPLAY = {
    "Vehicle": "Vehicle",
    "Pedestrian": "Pedestrian",
    "Cyclist": "Cyclist",
}


def cell(value) -> str:
    """Render a table cell, mapping missing/empty values to ``---``."""
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return "---"
    s = str(value).strip()
    if s == "" or s.lower() == "nan":
        return "---"
    return tex_escape(s)


def tex_escape(value: str) -> str:
    """Escape LaTeX-sensitive characters in a string cell."""
    return (
        str(value)
        .replace("\\", r"\textbackslash{}")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("#", r"\#")
        .replace("_", r"\_")
        .replace("$", r"\$")
        .replace("{", r"\{")
        .replace("}", r"\}")
        .replace("~", r"\textasciitilde{}")
        .replace("^", r"\textasciicircum{}")
    )


def fmt3(x) -> str:
    """Format a float to 3 decimal places."""
    try:
        return f"{float(x):.3f}"
    except (TypeError, ValueError):
        return tex_escape(str(x))


def fmt2(x) -> str:
    """Format a float to 2 decimal places."""
    try:
        return f"{float(x):.2f}"
    except (TypeError, ValueError):
        return tex_escape(str(x))


def fmt1(x) -> str:
    """Format a float to 1 decimal place."""
    try:
        return f"{float(x):.1f}"
    except (TypeError, ValueError):
        return tex_escape(str(x))


def fmt_int(x) -> str:
    """Format an integer with thousands separators."""
    try:
        return f"{int(round(float(x))):,}"
    except (TypeError, ValueError):
        return tex_escape(str(x))


def ordered(df: pd.DataFrame, key: str = "detector") -> pd.DataFrame:
    """Reorder a detector-indexed frame into the canonical display order."""
    out = df.copy()
    out[key] = out[key].map(lambda d: d if d in DETECTOR_ORDER else d)
    present = [d for d in DETECTOR_ORDER if d in set(out[key])]
    out[key] = pd.Categorical(out[key], categories=present, ordered=True)
    out = out.sort_values(key).reset_index(drop=True)
    out[key] = out[key].map(DISPLAY).fillna(out[key])
    return out


def begin_table(caption: str, label: str, colspec: str) -> list[str]:
    return [
        "\\begin{table}[t]",
        "    \\centering",
        f"    \\caption{{{caption}}}",
        f"    \\label{{{label}}}",
        f"    \\begin{{tabular}}{{{colspec}}}",
        "        \\toprule",
    ]


def end_table() -> list[str]:
    return [
        "        \\bottomrule",
        "    \\end{tabular}",
        "\\end{table}",
    ]


def write_table(filename: str, lines: list[str]) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / filename).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", OUT / filename)


# --------------------------------------------------------------------------- #
# Milestone 2 - dataset tables
# --------------------------------------------------------------------------- #
def table_dataset_comparison() -> None:
    src = ROOT / "docs" / "milestone_2" / "dataset_comparison_table.csv"
    df = pd.read_csv(src)
    df = df.set_index("metric")
    keep = [
        "Experimental role",
        "Source split",
        "Images",
        "Driving segments",
        "Target boxes",
        "Vehicle boxes",
        "Pedestrian boxes",
        "Cyclist boxes",
        "Images with no target boxes",
        "Camera",
        "Sampling rule",
        "Random seed",
    ]
    header = ["Metric", "KITTI (all)", "KITTI train", "KITTI val.", "Waymo ext."]
    cols = ["kitti_all", "kitti_train", "kitti_validation", "waymo_external_validation"]
    lines = begin_table(
        "Dataset composition and experimental roles of the three frozen partitions.",
        "tab:dataset_comparison",
        "lcccc",
    )
    lines.append("        " + " & ".join(header) + r" \\")
    lines.append("        \\midrule")
    for metric in keep:
        row = df.loc[metric]
        cells = [cell(metric)] + [cell(row[c]) for c in cols]
        lines.append("        " + " & ".join(cells) + r" \\")
    lines += end_table()
    write_table("tab_dataset_comparison.tex", lines)


def table_class_mapping() -> None:
    src = ROOT / "docs" / "milestone_2" / "class_mapping_table.csv"
    df = pd.read_csv(src)
    lines = begin_table(
        "Class harmonization mapping KITTI and Waymo annotations into the common "
        "Vehicle, Pedestrian, and Cyclist task.",
        "tab:class_mapping",
        "llll",
    )
    lines.append("        Dataset & Source class & Action & Unified class \\\\")
    lines.append("        \\midrule")
    for _, r in df.iterrows():
        ds = tex_escape(r["source_dataset"])
        sc = tex_escape(r["source_class_name"])
        action = tex_escape(r["action"])
        uc = tex_escape(r["unified_class_name"]) if pd.notna(r["unified_class_name"]) else "---"
        lines.append(f"        {ds} & {sc} & {action} & {uc} \\\\")
    lines += end_table()
    write_table("tab_class_mapping.tex", lines)


# --------------------------------------------------------------------------- #
# Milestone 5 - KITTI in-domain tables
# --------------------------------------------------------------------------- #
def table_kitti_results() -> None:
    src = ROOT / "outputs" / "milestone_5" / "figures" / "accuracy_comparison.csv"
    df = pd.read_csv(src)
    df = ordered(df)
    lines = begin_table(
        "KITTI in-domain detection results on the frozen validation split "
        "(1{,}496 images). Values are COCO Average Precision.",
        "tab:kitti_results",
        "lcccccc",
    )
    lines.append(
        "        Detector & mAP@0.50:0.95 & mAP@0.50 & mAP@0.75 & "
        "Vehicle AP & Pedestrian AP & Cyclist AP \\\\"
    )
    lines.append("        \\midrule")
    for _, r in df.iterrows():
        lines.append(
            "        "
            + " & ".join(
                [
                    r["detector"],
                    fmt3(r["mAP_50_95"]),
                    fmt3(r["mAP_50"]),
                    fmt3(r["mAP_75"]),
                    fmt3(r["Vehicle_AP"]),
                    fmt3(r["Pedestrian_AP"]),
                    fmt3(r["Cyclist_AP"]),
                ]
            )
            + r" \\"
        )
    lines += end_table()
    write_table("tab_kitti_results.tex", lines)


def table_efficiency() -> None:
    src = ROOT / "outputs" / "milestone_5" / "figures" / "efficiency_comparison.csv"
    df = pd.read_csv(src)
    df = ordered(df)
    lines = begin_table(
        "Deployment-oriented efficiency comparison on the local GPU.",
        "tab:efficiency",
        "lcccc",
    )
    lines.append(
        "        Detector & Parameters (M) & Checkpoint (MB) & Latency (ms) & FPS \\\\"
    )
    lines.append("        \\midrule")
    for _, r in df.iterrows():
        params_m = float(r["parameters"]) / 1e6
        lines.append(
            "        "
            + " & ".join(
                [
                    r["detector"],
                    fmt1(params_m),
                    fmt2(r["checkpoint_size_mb"]),
                    fmt2(r["latency_total_ms"]),
                    fmt2(r["frames_per_second"]),
                ]
            )
            + r" \\"
        )
    lines += end_table()
    write_table("tab_efficiency.tex", lines)


def table_operating_point() -> None:
    src = ROOT / "outputs" / "milestone_5" / "figures" / "operating_point_comparison.csv"
    df = pd.read_csv(src)
    df = ordered(df)
    lines = begin_table(
        "Operating-point metrics on KITTI validation "
        "(confidence $\\geq 0.25$, IoU $\\geq 0.50$).",
        "tab:operating_point",
        "lcccc",
    )
    lines.append("        Detector & Precision & Recall & F1 & FP/image \\\\")
    lines.append("        \\midrule")
    for _, r in df.iterrows():
        lines.append(
            "        "
            + " & ".join(
                [
                    r["detector"],
                    fmt3(r["precision"]),
                    fmt3(r["recall"]),
                    fmt3(r["f1_score"]),
                    fmt2(r["false_positives_per_image"]),
                ]
            )
            + r" \\"
        )
    lines += end_table()
    write_table("tab_operating_point.tex", lines)


# --------------------------------------------------------------------------- #
# Milestone 6 - Waymo external validation tables
# --------------------------------------------------------------------------- #
def table_waymo_results() -> None:
    src = (
        ROOT
        / "outputs"
        / "milestone_6"
        / "waymo_external_validation"
        / "tables"
        / "waymo_external_summary.csv"
    )
    df = pd.read_csv(src)
    df = ordered(df)
    lines = begin_table(
        "Waymo external-validation results (996 front-camera images, no retraining).",
        "tab:waymo_results",
        "lcccccc",
    )
    lines.append(
        "        Detector & mAP@0.50 & mAP@0.50:0.95 & Vehicle AP & "
        "Pedestrian AP & Cyclist AP & Mean inf. (ms) \\\\"
    )
    lines.append("        \\midrule")
    for _, r in df.iterrows():
        lines.append(
            "        "
            + " & ".join(
                [
                    r["detector"],
                    fmt3(r["mAP50"]),
                    fmt3(r["mAP50_95"]),
                    fmt3(r["Vehicle_AP50_95"]),
                    fmt3(r["Pedestrian_AP50_95"]),
                    fmt3(r["Cyclist_AP50_95"]),
                    fmt2(r["mean_inference_ms"]),
                ]
            )
            + r" \\"
        )
    lines += end_table()
    write_table("tab_waymo_results.tex", lines)


def table_kitti_vs_waymo() -> None:
    src = (
        ROOT
        / "outputs"
        / "milestone_6"
        / "generalization_analysis"
        / "tables"
        / "kitti_vs_waymo_comparison.csv"
    )
    df = pd.read_csv(src)
    df = ordered(df)
    lines = begin_table(
        "KITTI-to-Waymo degradation in mAP@0.50:0.95 and generalization ratio.",
        "tab:kitti_vs_waymo",
        "lccccc",
    )
    lines.append(
        "        Detector & KITTI mAP & Waymo mAP & Abs. drop & Drop (\\%) & "
        "Gen. ratio \\\\"
    )
    lines.append("        \\midrule")
    for _, r in df.iterrows():
        lines.append(
            "        "
            + " & ".join(
                [
                    r["detector"],
                    fmt3(r["KITTI_mAP50_95"]),
                    fmt3(r["Waymo_mAP50_95"]),
                    fmt3(r["mAP50_95_absolute_drop"]),
                    fmt2(r["mAP50_95_drop_percent"]),
                    fmt3(r["mAP50_95_generalization_ratio"]),
                ]
            )
            + r" \\"
        )
    lines += end_table()
    write_table("tab_kitti_vs_waymo.tex", lines)


def table_class_wise_degradation() -> None:
    src = (
        ROOT
        / "outputs"
        / "milestone_6"
        / "generalization_analysis"
        / "tables"
        / "class_wise_degradation.csv"
    )
    df = pd.read_csv(src)
    lines = begin_table(
        "Class-wise cross-dataset degradation in AP@0.50:0.95.",
        "tab:class_wise_degradation",
        "llcccc",
    )
    lines.append(
        "        Detector & Class & KITTI AP & Waymo AP & Abs. drop & Drop (\\%) \\\\"
    )
    lines.append("        \\midrule")
    for det in DETECTOR_ORDER:
        sub = df[df["detector"] == det]
        display = DISPLAY[det]
        for cls in ["Vehicle", "Pedestrian", "Cyclist"]:
            row = sub[sub["class_name"] == cls].iloc[0]
            first = display if cls == "Vehicle" else ""
            lines.append(
                "        "
                + " & ".join(
                    [
                        first,
                        cls,
                        fmt3(row["KITTI_AP50_95"]),
                        fmt3(row["Waymo_AP50_95"]),
                        fmt3(row["absolute_drop"]),
                        fmt2(row["drop_percent"]),
                    ]
                )
                + r" \\"
            )
        lines.append("        \\addlinespace")
    # remove trailing addlinespace
    if lines[-1].strip() == r"\addlinespace":
        lines.pop()
    lines += end_table()
    write_table("tab_class_wise_degradation.tex", lines)


# --------------------------------------------------------------------------- #
# Milestone 7 - robustness / safety tables
# --------------------------------------------------------------------------- #
def _size_recall_frame() -> pd.DataFrame:
    src = ROOT / "outputs" / "milestone_7" / "object_size_analysis" / "object_size_summary.csv"
    df = pd.read_csv(src)
    df = df[df["class_name"] == "all"]
    rows = []
    for det in DETECTOR_ORDER:
        record = {"detector": DISPLAY[det]}
        for ds in ["kitti", "waymo"]:
            for sz in ["small", "medium", "large"]:
                sub = df[(df["detector"] == det) & (df["dataset"] == ds) & (df["size_category"] == sz)]
                record[f"{ds}_{sz}"] = float(sub["recall"].iloc[0])
        rows.append(record)
    return pd.DataFrame(rows)


def table_object_size_recall() -> None:
    df = _size_recall_frame()
    lines = begin_table(
        "Class-agnostic recall by object-size category at the frozen operating point "
        "(confidence $\\geq 0.25$, IoU $\\geq 0.50$).",
        "tab:object_size_recall",
        "lcccccc",
    )
    lines.append(
        "        Detector & \\multicolumn{3}{c}{KITTI recall} & "
        "\\multicolumn{3}{c}{Waymo recall} \\\\"
    )
    lines.append(
        "        & Small & Medium & Large & Small & Medium & Large \\\\"
    )
    lines.append("        \\midrule")
    for _, r in df.iterrows():
        lines.append(
            "        "
            + " & ".join(
                [
                    r["detector"],
                    fmt3(r["kitti_small"]),
                    fmt3(r["kitti_medium"]),
                    fmt3(r["kitti_large"]),
                    fmt3(r["waymo_small"]),
                    fmt3(r["waymo_medium"]),
                    fmt3(r["waymo_large"]),
                ]
            )
            + r" \\"
        )
    lines += end_table()
    write_table("tab_object_size_recall.tex", lines)


def table_safety_fn() -> None:
    src = ROOT / "outputs" / "milestone_7" / "safety_error_analysis" / "safety_false_negative_summary.csv"
    df = pd.read_csv(src)
    df = df[df["class_name"] == "pedestrian+cyclist"]
    agg = (
        df.groupby(["dataset", "detector"])
        .agg(tp=("tp", "sum"), fn=("fn", "sum"))
        .reset_index()
    )
    agg["fn_rate"] = agg["fn"] / (agg["tp"] + agg["fn"])
    rows = []
    for det in DETECTOR_ORDER:
        record = {"detector": DISPLAY[det]}
        for ds in ["kitti", "waymo"]:
            sub = agg[(agg["detector"] == det) & (agg["dataset"] == ds)]
            record[f"{ds}_fn_rate"] = float(sub["fn_rate"].iloc[0])
        rows.append(record)
    frame = pd.DataFrame(rows)
    lines = begin_table(
        "Safety-critical false-negative rate for pedestrians and cyclists "
        "(operating point, confidence $\\geq 0.25$, IoU $\\geq 0.50$).",
        "tab:safety_fn",
        "lcc",
    )
    lines.append("        Detector & KITTI FN rate & Waymo FN rate \\\\")
    lines.append("        \\midrule")
    for _, r in frame.iterrows():
        lines.append(
            "        "
            + " & ".join(
                [
                    r["detector"],
                    fmt3(r["kitti_fn_rate"]),
                    fmt3(r["waymo_fn_rate"]),
                ]
            )
            + r" \\"
        )
    lines += end_table()
    write_table("tab_safety_fn.tex", lines)


def table_failure_type() -> None:
    src = ROOT / "outputs" / "milestone_7" / "safety_error_analysis" / "failure_type_summary.csv"
    df = pd.read_csv(src)
    cols = [
        ("true_positive", "TP"),
        ("false_negative", "Miss (FN)"),
        ("false_positive", "FP"),
        ("localization_error", "Localization"),
        ("class_confusion", "Confusion"),
        ("over_detection", "Over-detect."),
    ]
    header = ["Dataset", "Detector"] + [c[1] for c in cols]
    lines = begin_table(
        "Failure-type decomposition at the operating point for KITTI and Waymo.",
        "tab:failure_type",
        "l" + "l" + "c" * len(cols),
    )
    lines.append("        " + " & ".join(header) + r" \\")
    lines.append("        \\midrule")
    for ds in ["kitti", "waymo"]:
        ds_label = "KITTI" if ds == "kitti" else "Waymo"
        sub = df[df["dataset"] == ds]
        for det in DETECTOR_ORDER:
            r = sub[sub["detector"] == det].iloc[0]
            first = ds_label if det == DETECTOR_ORDER[0] else ""
            cells = [first, DISPLAY[det]] + [fmt_int(r[c[0]]) for c in cols]
            lines.append("        " + " & ".join(cells) + r" \\")
        lines.append("        \\addlinespace")
    if lines[-1].strip() == r"\addlinespace":
        lines.pop()
    lines += end_table()
    write_table("tab_failure_type.tex", lines)


def table_deployment() -> None:
    src = ROOT / "outputs" / "milestone_7" / "deployment_tradeoff" / "deployment_suitability_table.csv"
    df = pd.read_csv(src)
    df = ordered(df)
    lines = begin_table(
        "Deployment trade-off: in-domain accuracy, external accuracy, latency, "
        "and vulnerable-road-user (VRU) safety on Waymo.",
        "tab:deployment",
        "lccccc",
    )
    lines.append(
        "        Detector & KITTI mAP & Waymo mAP & Latency (ms) & "
        "Waymo VRU FN & Waymo VRU small recall \\\\"
    )
    lines.append("        \\midrule")
    for _, r in df.iterrows():
        lines.append(
            "        "
            + " & ".join(
                [
                    r["detector"],
                    fmt3(r["KITTI_mAP50_95"]),
                    fmt3(r["Waymo_mAP50_95"]),
                    fmt2(r["waymo_mean_inference_ms"]),
                    fmt3(r["Waymo_safety_fn_rate"]),
                    fmt3(r["Waymo_small_recall"]),
                ]
            )
            + r" \\"
        )
    lines += end_table()
    write_table("tab_deployment.tex", lines)


def main() -> None:
    print("=" * 79)
    print("Final paper - generate LaTeX tables from validated artifacts")
    print("=" * 79)
    table_dataset_comparison()
    table_class_mapping()
    table_kitti_results()
    table_efficiency()
    table_operating_point()
    table_waymo_results()
    table_kitti_vs_waymo()
    table_class_wise_degradation()
    table_object_size_recall()
    table_safety_fn()
    table_failure_type()
    table_deployment()
    print("Done.")


if __name__ == "__main__":
    main()
